Added --disable-shared option and STATIC_BUILD variable to be able to control the static vs. dynamic linking of the nsd executable. This is mainly for being able to check with purify memtool.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -16,6 +16,8 @@ ac_help="$ac_help
   --with-tcl              directory containing tcl configuration (tclConfig.sh)"
 ac_help="$ac_help
   --enable-symbols        build with debugging symbols [--disable-symbols]"
+ac_help="$ac_help
+  --enable-shared         build and link with shared libraries [--enable-shared]"
 
 # Initialize some variables set by options.
 # The variables have the same names as the options, with
@@ -507,8 +509,8 @@ fi
 ac_ext=c
 # CFLAGS is not in ac_cpp because -g, -O, etc. are not valid cpp options.
 ac_cpp='$CPP $CPPFLAGS'
-ac_compile='${CC-gcc} -c $CFLAGS $CPPFLAGS conftest.$ac_ext 1>&5'
-ac_link='${CC-gcc} -o conftest${ac_exeext} $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS 1>&5'
+ac_compile='${CC-cc} -c $CFLAGS $CPPFLAGS conftest.$ac_ext 1>&5'
+ac_link='${CC-cc} -o conftest${ac_exeext} $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS 1>&5'
 cross_compiling=$ac_cv_prog_cc_cross
 
 ac_exeext=
@@ -550,7 +552,7 @@ if test "${with_tcl+set}" = set; then
 fi
 
 	echo $ac_n "checking for Tcl configuration""... $ac_c" 1>&6
-echo "configure:554: checking for Tcl configuration" >&5
+echo "configure:556: checking for Tcl configuration" >&5
 	if eval "test \"`echo '$''{'ac_cv_c_tclconfig'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -623,7 +625,7 @@ fi
 
 
     echo $ac_n "checking for existence of $TCL_BIN_DIR/tclConfig.sh""... $ac_c" 1>&6
-echo "configure:627: checking for existence of $TCL_BIN_DIR/tclConfig.sh" >&5
+echo "configure:629: checking for existence of $TCL_BIN_DIR/tclConfig.sh" >&5
 
     if test -f "$TCL_BIN_DIR/tclConfig.sh" ; then
         echo "$ac_t""loading" 1>&6
@@ -671,17 +673,12 @@ echo "configure:627: checking for existence of $TCL_BIN_DIR/tclConfig.sh" >&5
     
     
 
-if test "${TCL_THREADS}" != "1"
-then
+if test "${TCL_THREADS}" != "1"; then
     { echo "configure: error: must build tcl with --enable-threads" 1>&2; exit 1; }
-fi
-if test "${TCL_SHARED_BUILD}" != "1"
-then
-    { echo "configure: error: must build tcl with --enable-sahred" 1>&2; exit 1; }
 fi
 
     echo $ac_n "checking for build with symbols""... $ac_c" 1>&6
-echo "configure:685: checking for build with symbols" >&5
+echo "configure:682: checking for build with symbols" >&5
     # Check whether --enable-symbols or --disable-symbols was given.
 if test "${enable_symbols+set}" = set; then
   enableval="$enable_symbols"
@@ -691,19 +688,47 @@ else
 fi
 
 # FIXME: Currently, LDFLAGS_DEFAULT is not used, it should work like CFLAGS_DEFAULT.
-    if test "$tcl_ok" = "yes"; then
-	CFLAGS_DEFAULT='$(CFLAGS_DEBUG)'
-	LDFLAGS_DEFAULT='$(LDFLAGS_DEBUG)'
-	DBGX=g
-	echo "$ac_t""yes" 1>&6
-    else
+    if test "$tcl_ok" = "no"; then
 	CFLAGS_DEFAULT='$(CFLAGS_OPTIMIZE)'
 	LDFLAGS_DEFAULT='$(LDFLAGS_OPTIMIZE)'
 	DBGX=""
 	echo "$ac_t""no" 1>&6
+    else
+	CFLAGS_DEFAULT='$(CFLAGS_DEBUG)'
+	LDFLAGS_DEFAULT='$(LDFLAGS_DEBUG)'
+	DBGX=g
+	if test "$tcl_ok" = "yes"; then
+	    echo "$ac_t""yes (standard debugging)" 1>&6
+	fi
     fi
     
     
+
+    if test "$tcl_ok" = "mem" -o "$tcl_ok" = "all"; then
+	cat >> confdefs.h <<\EOF
+#define TCL_MEM_DEBUG 1
+EOF
+
+    fi
+
+    if test "$tcl_ok" = "compile" -o "$tcl_ok" = "all"; then
+	cat >> confdefs.h <<\EOF
+#define TCL_COMPILE_DEBUG 1
+EOF
+
+	cat >> confdefs.h <<\EOF
+#define TCL_COMPILE_STATS 1
+EOF
+
+    fi
+
+    if test "$tcl_ok" != "yes" -a "$tcl_ok" != "no"; then
+	if test "$tcl_ok" = "all"; then
+	    echo "$ac_t""enabled symbols mem compile debugging" 1>&6
+	else
+	    echo "$ac_t""enabled $tcl_ok debugging" 1>&6
+	fi
+    fi
 
 
 
@@ -728,6 +753,7 @@ fi
 #
 # TCL_SHLIB_LD from tclConfig.sh is not quite right for aolserver.
 #
+
 test "x$prefix" = "xNONE" && prefix="/usr/local/aolserver"
 system=`uname`
 case "$system" in
@@ -785,12 +811,12 @@ AOLSERVER=$prefix
 for ac_func in timegm fork1 poll drand48 random _NSGetEnviron
 do
 echo $ac_n "checking for $ac_func""... $ac_c" 1>&6
-echo "configure:789: checking for $ac_func" >&5
+echo "configure:815: checking for $ac_func" >&5
 if eval "test \"`echo '$''{'ac_cv_func_$ac_func'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 794 "configure"
+#line 820 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char $ac_func(); below.  */
@@ -813,7 +839,7 @@ $ac_func();
 
 ; return 0; }
 EOF
-if { (eval echo configure:817: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:843: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_func_$ac_func=yes"
 else
@@ -838,7 +864,7 @@ fi
 done
 
 echo $ac_n "checking how to run the C preprocessor""... $ac_c" 1>&6
-echo "configure:842: checking how to run the C preprocessor" >&5
+echo "configure:868: checking how to run the C preprocessor" >&5
 # On Suns, sometimes $CPP names a directory.
 if test -n "$CPP" && test -d "$CPP"; then
   CPP=
@@ -848,18 +874,18 @@ if eval "test \"`echo '$''{'ac_cv_prog_CPP'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
     # This must be in double quotes, not single quotes, because CPP may get
-  # substituted into the Makefile and "${CC-gcc}" will confuse make.
-  CPP="${CC-gcc} -E"
+  # substituted into the Makefile and "${CC-cc}" will confuse make.
+  CPP="${CC-cc} -E"
   # On the NeXT, cc -E runs the code through the compiler's parser,
   # not just through cpp.
   cat > conftest.$ac_ext <<EOF
-#line 857 "configure"
+#line 883 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:863: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:889: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   :
@@ -868,15 +894,15 @@ else
   echo "configure: failed program was:" >&5
   cat conftest.$ac_ext >&5
   rm -rf conftest*
-  CPP="${CC-gcc} -E -traditional-cpp"
+  CPP="${CC-cc} -E -traditional-cpp"
   cat > conftest.$ac_ext <<EOF
-#line 874 "configure"
+#line 900 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:880: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:906: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   :
@@ -885,15 +911,15 @@ else
   echo "configure: failed program was:" >&5
   cat conftest.$ac_ext >&5
   rm -rf conftest*
-  CPP="${CC-gcc} -nologo -E"
+  CPP="${CC-cc} -nologo -E"
   cat > conftest.$ac_ext <<EOF
-#line 891 "configure"
+#line 917 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:897: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:923: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   :
@@ -919,17 +945,17 @@ echo "$ac_t""$CPP" 1>&6
 
 ac_safe=`echo "mach-o/dyld.h" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for mach-o/dyld.h""... $ac_c" 1>&6
-echo "configure:923: checking for mach-o/dyld.h" >&5
+echo "configure:949: checking for mach-o/dyld.h" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 928 "configure"
+#line 954 "configure"
 #include "confdefs.h"
 #include <mach-o/dyld.h>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:933: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:959: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -955,17 +981,17 @@ fi
 
 ac_safe=`echo "dl.h" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for dl.h""... $ac_c" 1>&6
-echo "configure:959: checking for dl.h" >&5
+echo "configure:985: checking for dl.h" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 964 "configure"
+#line 990 "configure"
 #include "confdefs.h"
 #include <dl.h>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:969: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:995: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -990,12 +1016,12 @@ else
 fi
 
 echo $ac_n "checking need for dup high""... $ac_c" 1>&6
-echo "configure:994: checking need for dup high" >&5
+echo "configure:1020: checking need for dup high" >&5
 if test "$cross_compiling" = yes; then
   as_ok=no
 else
   cat > conftest.$ac_ext <<EOF
-#line 999 "configure"
+#line 1025 "configure"
 #include "confdefs.h"
 
 #include <stdio.h>
@@ -1005,7 +1031,7 @@ main(int argc, char **argv)
     return (sizeof(stdout->_file) == 1) ? 0 : 1;
 }
 EOF
-if { (eval echo configure:1009: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:1035: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   as_ok=yes
 else
@@ -1027,9 +1053,9 @@ EOF
 fi
 
 echo $ac_n "checking msg_controllen in struct msghdr""... $ac_c" 1>&6
-echo "configure:1031: checking msg_controllen in struct msghdr" >&5
+echo "configure:1057: checking msg_controllen in struct msghdr" >&5
 cat > conftest.$ac_ext <<EOF
-#line 1033 "configure"
+#line 1059 "configure"
 #include "confdefs.h"
 
 #include <sys/types.h>
@@ -1041,7 +1067,7 @@ int *i = msg.msg_controllen;
 
 ; return 0; }
 EOF
-if { (eval echo configure:1045: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:1071: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   as_ok=yes
 else
@@ -1059,6 +1085,45 @@ then
 EOF
 
 fi
+
+#
+# Normally, we'd link the resulting server image
+# dynamically. In some cases it is however more
+# appropriate to build it as a monolithic image.
+#
+
+echo $ac_n "checking how to build server image""... $ac_c" 1>&6
+echo "configure:1097: checking how to build server image" >&5
+# Check whether --enable-shared or --disable-shared was given.
+if test "${enable_shared+set}" = set; then
+  enableval="$enable_shared"
+  shared_ok=$enableval
+else
+  shared_ok=yes
+fi
+
+if test "${enable_shared+set}" = set; then
+    enableval="$enable_shared"
+    shared_ok=$enableval
+else
+    shared_ok=yes
+fi
+if test "$shared_ok" = "yes" ; then
+    if test "${TCL_SHARED_BUILD}" != "1"
+    then
+        { echo "configure: error: must build tcl with --enable-shared" 1>&2; exit 1; }
+    fi
+    STATIC_BUILD=0
+    echo "$ac_t""shared" 1>&6
+else
+    if test "${TCL_SHARED_BUILD}" != "0"
+    then
+        { echo "configure: error: must build tcl with --disable-shared" 1>&2; exit 1; }
+    fi
+    STATIC_BUILD=1
+    echo "$ac_t""static" 1>&6
+fi
+
 
 #
 # Create Makefile.global.
@@ -1245,6 +1310,7 @@ s%@CCRPATHS@%$CCRPATHS%g
 s%@LDRPATHS@%$LDRPATHS%g
 s%@AOLSERVER@%$AOLSERVER%g
 s%@CPP@%$CPP%g
+s%@STATIC_BUILD@%$STATIC_BUILD%g
 
 CEOF
 EOF
