Created a special test for USE_DUPHIGH and eliminated need for platform-specific USE_DLSYMPREFIX.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2126,6 +2126,52 @@ EOF
 
 fi
 
+echo "$as_me:2129: checking need for dup high" >&5
+echo $ECHO_N "checking need for dup high... $ECHO_C" >&6
+if test "$cross_compiling" = yes; then
+  duphigh=no
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line 2135 "configure"
+#include "confdefs.h"
+
+#include <stdio.h>
+int
+main(int argc, char **argv)
+{
+	return (sizeof(stdout->_file) == 1) ? 0 : 1;
+}
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:2146: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:2149: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:2151: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:2154: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  duphigh=yes
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+duphigh=no
+fi
+rm -f core core.* *.core conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+if test "${duphigh}" = "yes"
+then
+    cat >>confdefs.h <<\EOF
+#define USE_DUPHIGH 1
+EOF
+
+fi
+echo "$as_me:2172: result: $duphigh" >&5
+echo "${ECHO_T}$duphigh" >&6
+
 #
 # Create Makefile.global.
 #
@@ -2242,7 +2288,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:2245: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:2291: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -2409,7 +2455,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:2412: error: ambiguous option: $1
+    { { echo "$as_me:2458: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -2428,7 +2474,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:2431: error: unrecognized option: $1
+  -*) { { echo "$as_me:2477: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -2464,7 +2510,7 @@ do
   case "$ac_config_target" in
   # Handling of arguments.
   "include/Makefile.global" ) CONFIG_FILES="$CONFIG_FILES include/Makefile.global" ;;
-  *) { { echo "$as_me:2467: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:2513: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -2684,7 +2730,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:2687: creating $ac_file" >&5
+    { echo "$as_me:2733: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -2702,7 +2748,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:2705: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:2751: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -2715,7 +2761,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:2718: error: cannot find input file: $f" >&5
+           { { echo "$as_me:2764: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
